### ISSUE TITLE
Create a test suite to check accuracy of citation detection

### ISSUE THREAD

**Issue by lmullen** [lmullen/legal-modernism#34]
This would be a spreadsheet with three (or four) columns:
1. The text of the citation as you expect to find it in the wild. This may or may not include surrounding text, depending on the test.
2. The cleaned, normalized text of the citation.
3. Optionally, the citation as it would be found in CAP.
4. A brief description of what is being tested in that case: (e.g., Citation with pincite, Citation to antique reporter etc.)

**Comment by lmullen** [comment]
We might also eventually add a column for the URL of the case in CAP.

**Comment by lmullen** [comment]
From @kfunk074, the start of a test suite.

[citation detection tests.xlsx](https://github.com/lmullen/legal-modernism/files/7529809/citation.detection.tests.xlsx)

**Comment by lmullen** [comment]
Just a few of the most straightforward examples that should be added to this:

- [ ] Kelly or other antique reporters
- [ ] Oreg. vs Or. and other variations in abbreviation
- [ ] British citations

**Comment by kfunk074** [comment]
> Just a few of the most straightforward examples that should be added to this:
> 
> * [ ]  Kelly or other antique reporters
> * [ ]  Oreg. vs Or. and other variations in abbreviation
> * [ ]  British citations

We already know eyecite misses these as currently constituted. The test suite I've written is to check what kinds of OCR errors eyecite struggles with, if any.

**Comment by lmullen** [comment]
Right. But we will eventually want to test for every kind of thing to see whether we are finding citations.

**Comment by lmullen** [comment]
This is basically done, in the sense that we can add citations that have caused us problems and know that they are fixed. And we are also checking this manually. So this is as done as it is going to be.
