### ISSUE TITLE
Create tables of antique reporters and their corresponding standard citations

### ISSUE THREAD

**Issue by lmullen** [lmullen/legal-modernism#37]

**Comment by lmullen** [comment]
For the reporter corrections, the best thing would probably be to a volume to volume (rather than series to series) correspondence. And the columns for volume numbers should be broken out. In other words (with four columns):
1 Kelley -> 1 Ga.
2 Kelley -> 2 Ga.
3 Kelley -> 3 Ga.
1 Oregon -> 2 Oregon

**Comment by lmullen** [comment]
[CAP Fixes.xlsx](https://github.com/lmullen/legal-modernism/files/7529883/CAP.Fixes.xlsx)

A first step towards some of this.

**Comment by kfunk074** [comment]
Updated list, accounting for all of Georgia and South Carolina. SC is one of the worst states for nominate reporters. There should not be quite so many moving forward. 
[CAP Fixes_12.4.2021.xlsx](https://github.com/lmullen/legal-modernism/files/7671586/CAP.Fixes_12.4.2021.xlsx)

**Comment by kfunk074** [comment]
Most recent update:
[CAP Fixes_12.17.2021.xlsx](https://github.com/lmullen/legal-modernism/files/7872085/CAP.Fixes_12.17.2021.xlsx)

**Comment by kfunk074** [comment]
Most recent update:
[CAP Fixes_2.15.xlsx](https://github.com/lmullen/legal-modernism/files/8080209/CAP.Fixes_2.15.xlsx)

Here's what Sean says is covered:

AK/HI
West: WA/OR/CA/NV/ID/MT/UT/AZ/NM/CO/WY

East: SC/NC/VA/WV/MS/TN/FL/GA/AL/LA/KY/LA/D.C.

He's also made some notes on quirks and unusual entries: 
[Memo_Unusual_Things.docx](https://github.com/lmullen/legal-modernism/files/8080216/Memo_Unusual_Things.docx)

**Comment by kfunk074** [comment]
Most recent update:
[CAP Fixes_3.25.xlsx](https://github.com/lmullen/legal-modernism/files/8354007/CAP.Fixes_3.25.xlsx)

The list of states covered is as follows:
AK/HI
 
West: WA/OR/CA/NV/ID/MT/UT/AZ/NM/CO/WY
 
Mid: TX/KS/OK/NE/SD/ND/MN/IA/MO/AR/WI/IL/IN/OH
 
East: SC/NC/VA/WV/MS/TN/FL/GA/AL/LA/KY/LA/D.C./ME/NH/VT/RI/CT/NJ
+ SC nominative reporters

**Comment by kfunk074** [comment]
Most recent update:
[CAP Fixes_4.9.xlsx](https://github.com/lmullen/legal-modernism/files/8517513/CAP.Fixes_4.9.xlsx)

**Comment by lmullen** [comment]
This is in the database now.
