### ISSUE TITLE
Create method for linking antique reporter to standard reporter

### ISSUE THREAD

**Issue by lmullen** [lmullen/legal-modernism#38]
Presumably this will happen as a set of joins in the database, but let's see.

**Comment by kfunk074** [comment]
[CAP Fixes_4.29.xlsx](https://github.com/lmullen/legal-modernism/files/9427156/CAP.Fixes_4.29.xlsx)

Sean's last update on nominate reporters and their correspondences in CAP. A good test would be Dickinson's Chancery Reports, which are often cited as such, but CAP only knows the cases by their N.J. Eq. appearances. There's basically two variations of the cite in the treatises: **Dick.** and **Dick. Ch. Rep.**. Can we match cites to those cases to the appropriate volume and case in N.J. Eq. to join up the CAP data? And do it in a way that Sean's data will help automate the rest of the linking process for other nominate reporters?

**Comment by lmullen** [comment]
This specific set of concerns has been superseded.
