### ISSUE TITLE
Dump database of citations for RAs

### ISSUE THREAD

**Issue by lmullen** [lmullen/legal-modernism#86]

**Comment by lmullen** [comment]
Going to finish #76 and then do this.

Database is 86GB, but only 30GB excluding the full text of CAP and of MOML.

**Comment by kfunk074** [comment]
Full text of MOML (can limit to US treatises) would be useful for RAs to run comparative tests with eyecite. Can include in database dump or upload separately to a Google Drive.

**Comment by lmullen** [comment]
Would they know how to work with a PostgreSQL data dump, or do they need CSVs? Either is fine.

**Comment by kfunk074** [comment]
PostgreSQL should be fine.
