### ISSUE TITLE
Resolve volume problem for MOML treatises

### ISSUE THREAD

**Issue by lmullen** [lmullen/legal-modernism#87]
The `psmid` field in the MOML database uniquely identifies a volume. Is there a unique identifier for a treatise, which encompasses all of the volumes in the same edition? 

A related problem might be linking treatises published in different editions.

**Comment by kfunk074** [comment]
The web interface is pretty limited. Can @lmullen post a csv of MOML data associated with James Kent? I can try to figure out the work/volume/edition signifiers from there.

**Comment by lmullen** [comment]
I know how to solve this now. The correct field is `bibliographicid` on the `moml.book_info` table.

This will find all the multivolume works:

```
select bibliographicid, count(*) as n
from moml.book_info
group by bibliographicid
having count(*) > 1
order by n desc;
```

For a given bibliographic ID, this will return all the volumes.

```
select bi.bibliographicid, bi.psmid, bi.year, bc.currentvolume, bc.displaytitle
from moml.book_info bi
left join moml.book_citation bc on bi.psmid = bc.psmid
where bi.bibliographicid = 'CTRG95-B1363'
order by year, currentvolume::int;
```
